# Generated by Django 4.2.1 on 2025-08-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_auto_generate_asset_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_base_url', models.URLField(default='http://localhost:8001', help_text='Base URL of CRM system')),
                ('crm_api_key', models.CharField(blank=True, help_text='API key for CRM authentication', max_length=255)),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Enable automatic synchronization')),
                ('sync_interval_minutes', models.IntegerField(default=30, help_text='Sync interval in minutes')),
                ('sync_customers_to_assets', models.BooleanField(default=True, help_text='Sync CRM customers to Asset Manager')),
                ('sync_assets_to_crm', models.BooleanField(default=True, help_text='Sync Asset assignments to CRM')),
                ('sync_employees', models.BooleanField(default=True, help_text='Sync employee data between systems')),
                ('customer_assignment_field_mapping', models.JSONField(blank=True, default=dict, help_text='Field mapping configuration')),
                ('notify_on_sync_error', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, help_text='Email for sync notifications', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Settings',
                'verbose_name_plural': 'Integration Settings',
            },
        ),
        migrations.CreateModel(
            name='CRMCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_customer_id', models.IntegerField(help_text='ID from CRM system', unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('customer_type', models.CharField(default='individual', max_length=20)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending Sync'), ('error', 'Sync Error')], default='synced', max_length=20)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCustomerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_type', models.CharField(choices=[('owned', 'Owned by Customer'), ('leased', 'Leased to Customer'), ('serviced', 'Under Service Contract'), ('temporary', 'Temporary Assignment')], default='owned', max_length=20)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to='assets.asset')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='crm_integration.crmcustomer')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('customer_to_asset', 'Customer → Asset Manager'), ('asset_to_crm', 'Asset Manager → CRM'), ('employee_sync', 'Employee Synchronization'), ('assignment_sync', 'Assignment Synchronization')], max_length=30)),
                ('sync_action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('sync', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success'), ('pending', 'Pending')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_success', models.IntegerField(default=0)),
                ('records_error', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('sync_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sync_type', 'status'], name='crm_integra_sync_ty_9aff10_idx'), models.Index(fields=['started_at'], name='crm_integra_started_b6baa6_idx'), models.Index(fields=['sync_id'], name='crm_integra_sync_id_75e363_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crmcustomer',
            index=models.Index(fields=['crm_customer_id'], name='crm_integra_crm_cus_68ef95_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcustomer',
            index=models.Index(fields=['email'], name='crm_integra_email_8e3c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='crmcustomer',
            index=models.Index(fields=['assigned_employee'], name='crm_integra_assigne_67e873_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcustomerassignment',
            index=models.Index(fields=['asset', 'is_active'], name='crm_integra_asset_i_c1e23f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcustomerassignment',
            index=models.Index(fields=['customer', 'is_active'], name='crm_integra_custome_0db13a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcustomerassignment',
            index=models.Index(fields=['assignment_type'], name='crm_integra_assignm_527f41_idx'),
        ),
    ]
