#!/usr/bin/env python
"""
Create missing auth_user_groups table
"""

import os
import sys
import django

def create_auth_user_groups():
    """Create the missing auth_user_groups table"""
    print("Creating auth_user_groups table...")

    # Set environment variables
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'assetmanager.settings')

    # Add Django project to path
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'assetmanagement'))

    # Setup Django
    django.setup()

    from django.db import connection

    with connection.cursor() as cursor:
        # Create the table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS "auth_user_groups" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "user_id" integer NOT NULL,
                "group_id" integer NOT NULL
            )
        ''')

        # Add constraints
        cursor.execute('''
            ALTER TABLE "auth_user_groups"
            ADD CONSTRAINT IF NOT EXISTS "auth_user_groups_user_id_group_id_94350c0c_uniq"
            UNIQUE ("user_id", "group_id")
        ''')

        cursor.execute('''
            ALTER TABLE "auth_user_groups"
            ADD CONSTRAINT IF NOT EXISTS "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id"
            FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
        ''')

        cursor.execute('''
            ALTER TABLE "auth_user_groups"
            ADD CONSTRAINT IF NOT EXISTS "auth_user_groups_group_id_97559544_fk_auth_group_id"
            FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED
        ''')

        # Create indexes
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS "auth_user_groups_user_id_6a12ed8b"
            ON "auth_user_groups" ("user_id")
        ''')

        cursor.execute('''
            CREATE INDEX IF NOT EXISTS "auth_user_groups_group_id_97559544"
            ON "auth_user_groups" ("group_id")
        ''')

        print("✓ auth_user_groups table created")

if __name__ == '__main__':
    create_auth_user_groups()
    print("✅ Auth user groups table created successfully!")
