# Generated by Django 4.2.7 on 2025-07-10 17:09

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='device_id',
            field=models.CharField(blank=True, help_text='Device ID', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_name',
            field=models.CharField(blank=True, help_text='Device name (e.g., DESKTOP-2ANTBJU)', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='installed_ram',
            field=models.CharField(blank=True, help_text='RAM information (e.g., 16.0 GB)', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, help_text='Processor information', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='product_id',
            field=models.CharField(blank=True, help_text='Product ID', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='system_type',
            field=models.CharField(blank=True, help_text='System type (e.g., 64-bit operating system)', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, default=assets.models.generate_serial_number, max_length=100),
        ),
    ]
