# Generated by Django 4.2.7 on 2025-07-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_device_id_asset_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
