# Generated by Django 4.2.1 on 2025-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_worksession_timeentry_task_employeekpi_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('call_center', 'Call Center'), ('sales', 'Sales'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role'], name='crm_employe_role_babf66_idx'),
        ),
    ]
