# Generated by Django 4.2.1 on 2025-10-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_employee_role_employee_crm_employe_role_babf66_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('call_center', 'Call Center'), ('sales', 'Sales'), ('user', 'User'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('project_support', 'Project Support'), ('hr', 'HR'), ('project_manager', 'Project Manager'), ('dev', 'Developer')], default='user', max_length=20),
        ),
    ]
