# Generated by Django 4.2.1 on 2025-10-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=100)),
                ('caller_phone', models.CharField(max_length=20)),
                ('caller_company', models.CharField(blank=True, max_length=100)),
                ('missed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason_for_call', models.TextField(blank=True, help_text='Why was the caller calling?')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Callback'), ('attempted', 'Callback Attempted'), ('completed', 'Callback Completed'), ('no_callback_needed', 'No Callback Needed')], default='pending', max_length=20)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('callback_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('callback_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_callbacks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_calls', to='crm.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_calls', to='crm.employee')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_calls', to='crm.lead')),
            ],
            options={
                'ordering': ['-missed_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='crm_missedc_employe_7f2a84_idx'), models.Index(fields=['status', 'priority'], name='crm_missedc_status_80dff6_idx'), models.Index(fields=['missed_at'], name='crm_missedc_missed__0142e4_idx'), models.Index(fields=['caller_phone'], name='crm_missedc_caller__c88c69_idx')],
            },
        ),
    ]
