# Generated by Django 4.2.1 on 2025-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_missedcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='duration_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration in minutes (e.g., 2.5 = 2 min 30 sec)', max_digits=6, null=True),
        ),
    ]
