# Generated by Django 4.2.1 on 2025-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_communication_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='is_sourced',
            field=models.BooleanField(default=False, help_text='Indicates if this contact was sourced'),
        ),
    ]
