# Generated by Django 4.2.1 on 2025-10-07 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_communication_is_sourced'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='idle_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Time without activity', max_digits=5),
        ),
        migrations.AddField(
            model_name='worksession',
            name='productive_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Time with activity', max_digits=5),
        ),
        migrations.CreateModel(
            name='MonitoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_threshold', models.IntegerField(default=300, help_text='Seconds of inactivity before considered idle (default: 5 minutes)')),
                ('extended_idle_threshold', models.IntegerField(default=900, help_text='Seconds for extended idle warning (default: 15 minutes)')),
                ('enable_monitoring', models.BooleanField(default=True, help_text='Enable activity monitoring for this employee')),
                ('enable_idle_alerts', models.BooleanField(default=True, help_text='Send alerts when idle threshold is reached')),
                ('enable_screenshots', models.BooleanField(default=False, help_text='Enable periodic screenshots (if implemented)')),
                ('heartbeat_interval', models.IntegerField(default=60, help_text='How often to send activity data (default: 60 seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_settings', to='crm.employee')),
            ],
            options={
                'verbose_name': 'Monitoring Settings',
                'verbose_name_plural': 'Monitoring Settings',
            },
        ),
        migrations.CreateModel(
            name='IdlePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Duration of idle period in seconds')),
                ('is_extended_idle', models.BooleanField(default=False, help_text='Idle period exceeded extended threshold')),
                ('reason', models.CharField(blank=True, help_text='Reason for idle time (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_periods', to='crm.employee')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_periods', to='crm.worksession')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['employee', 'start_time'], name='crm_idleper_employe_3a7c88_idx'), models.Index(fields=['work_session', 'start_time'], name='crm_idleper_work_se_fa2d0d_idx'), models.Index(fields=['start_time', 'end_time'], name='crm_idleper_start_t_e51347_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mouse_movements', models.IntegerField(default=0)),
                ('total_mouse_clicks', models.IntegerField(default=0)),
                ('total_keyboard_events', models.IntegerField(default=0)),
                ('total_scroll_events', models.IntegerField(default=0)),
                ('total_active_time', models.IntegerField(default=0, help_text='Total time with activity in seconds')),
                ('total_idle_time', models.IntegerField(default=0, help_text='Total idle time in seconds')),
                ('productivity_score', models.DecimalField(decimal_places=2, default=0, help_text='Calculated productivity score', max_digits=5)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to='crm.employee')),
                ('work_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_session', to='crm.worksession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'created_at'], name='crm_activit_employe_6442b2_idx'), models.Index(fields=['work_session'], name='crm_activit_work_se_4bdeed_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('mouse_move', 'Mouse Movement'), ('mouse_click', 'Mouse Click'), ('keyboard', 'Keyboard Input'), ('scroll', 'Scroll'), ('window_focus', 'Window Focus'), ('window_blur', 'Window Blur'), ('heartbeat', 'Heartbeat Signal')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional activity details (coordinates, keys, etc.)')),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='crm.employee')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='crm.worksession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='crm_activit_employe_c151a4_idx'), models.Index(fields=['work_session', 'timestamp'], name='crm_activit_work_se_6bc104_idx'), models.Index(fields=['activity_type', 'timestamp'], name='crm_activit_activit_581b87_idx'), models.Index(fields=['timestamp'], name='crm_activit_timesta_693025_idx')],
            },
        ),
    ]
