# Generated by Django 5.2.7 on 2025-11-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_worksession_idle_hours_worksession_productive_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_entity', models.CharField(max_length=255)),
                ('to_entity', models.CharField(max_length=255)),
                ('request_date', models.DateField()),
                ('amount', models.PositiveIntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_requests', to='crm.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='crm_moneyre_status_d93900_idx'), models.Index(fields=['employee', 'status'], name='crm_moneyre_employe_20c1a0_idx'), models.Index(fields=['request_date'], name='crm_moneyre_request_5283e9_idx')],
            },
        ),
    ]
