# Generated by Django 5.2.7 on 2025-11-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_moneyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_money_requests', to='crm.employee'),
        ),
    ]
