# Generated by Django 5.2.7 on 2025-12-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_moneyrequest_decision_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('call_center', 'Call Center'), ('sales', 'Sales'), ('user', 'User'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('project_support', 'Project Support'), ('hr', 'HR'), ('project_manager', 'Project Manager'), ('dev', 'Developer'), ('handler', 'Handler')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='HandlerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('weekly_target', models.IntegerField(default=10)),
                ('calls_made', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('errands_made', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handler_reports', to='crm.employee')),
            ],
            options={
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['handler', 'week_start'], name='crm_handler_handler_c6aea9_idx'), models.Index(fields=['week_start'], name='crm_handler_week_st_c390fb_idx')],
                'unique_together': {('handler', 'week_start')},
            },
        ),
    ]
