# Generated by Django 5.2.7 on 2025-12-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_employee_daily_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='daily_target',
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_target',
            field=models.IntegerField(default=10, help_text='Weekly call target for this employee'),
        ),
    ]
