# Generated by Django 4.2.7 on 2026-10-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_leavebalance_id_alter_leaverequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='zkteco_id',
            field=models.CharField(blank=True, help_text='User ID enrolled on the ZKTeco fingerprint device (e.g. 1, 2, 3...)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual (Web)'), ('device', 'ZKTeco Device')], default='manual', max_length=20),
        ),
    ]
