# Generated by Django 4.2.7 on 2025-07-11 08:33

from django.db import migrations
from django.db import transaction
from datetime import datetime


def generate_employee_id_for_migration():
    """Generate a unique employee ID with format EMP-YYYY-NNNN"""
    current_year = datetime.now().year
    
    def _generate_id(apps, schema_editor):
        UserProfile = apps.get_model('users', 'UserProfile')
        
        year_prefix = f"EMP-{current_year}-"
        existing_ids = UserProfile.objects.filter(
            employee_id__startswith=year_prefix
        ).values_list('employee_id', flat=True)
        
        # Extract numbers from existing IDs
        numbers = []
        for emp_id in existing_ids:
            try:
                # Extract the 4-digit number part
                number_part = emp_id.split('-')[-1]
                if number_part.isdigit() and len(number_part) == 4:
                    numbers.append(int(number_part))
            except (IndexError, ValueError):
                continue
        
        # Get next number
        next_number = max(numbers) + 1 if numbers else 1
        
        # Format with leading zeros (4 digits)
        return f"EMP-{current_year}-{next_number:04d}"
    
    return _generate_id


def populate_employee_ids(apps, schema_editor):
    """Populate employee IDs for existing user profiles"""
    UserProfile = apps.get_model('users', 'UserProfile')
    
    profiles_without_ids = UserProfile.objects.filter(employee_id__in=['', None])
    
    for profile in profiles_without_ids:
        # Generate unique employee ID
        current_year = datetime.now().year
        year_prefix = f"EMP-{current_year}-"
        
        existing_ids = UserProfile.objects.filter(
            employee_id__startswith=year_prefix
        ).values_list('employee_id', flat=True)
        
        # Extract numbers from existing IDs
        numbers = []
        for emp_id in existing_ids:
            try:
                number_part = emp_id.split('-')[-1]
                if number_part.isdigit() and len(number_part) == 4:
                    numbers.append(int(number_part))
            except (IndexError, ValueError):
                continue
        
        # Get next number
        next_number = max(numbers) + 1 if numbers else 1
        
        # Generate and assign employee ID
        employee_id = f"EMP-{current_year}-{next_number:04d}"
        profile.employee_id = employee_id
        profile.save()


def reverse_populate_employee_ids(apps, schema_editor):
    """Reverse the employee ID population"""
    UserProfile = apps.get_model('users', 'UserProfile')
    # Clear all auto-generated employee IDs
    current_year = datetime.now().year
    UserProfile.objects.filter(employee_id__startswith=f"EMP-{current_year}-").update(employee_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_employee_ids, reverse_populate_employee_ids),
    ]
