# Generated by Django 4.2.7 on 2025-07-11 08:58

from django.db import migrations
from django.db.models import Count


def clean_duplicate_profiles(apps, schema_editor):
    """Remove duplicate UserProfile records, keeping the newest one"""
    UserProfile = apps.get_model('users', 'UserProfile')
    
    # Find users with multiple profiles
    duplicate_users = UserProfile.objects.values('user').annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    for item in duplicate_users:
        user_id = item['user']
        profiles = UserProfile.objects.filter(user_id=user_id).order_by('-id')
        
        # Keep the newest profile, delete the rest
        profiles_to_delete = profiles[1:]
        for profile in profiles_to_delete:
            profile.delete()
            print(f"Deleted duplicate profile for user_id {user_id}")


def reverse_clean_duplicate_profiles(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_unique_user_profile'),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_profiles, reverse_clean_duplicate_profiles),
    ]
