# Generated by Django 4.2.30 on 2026-08-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rider_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
