# Generated by Django 4.2.7 on 2026-10-03 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0015_alter_leavebalance_id_alter_leaverequest_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('warning', 'Written Warning'), ('commendation', 'Commendation'), ('performance', 'Performance Review'), ('disciplinary', 'Disciplinary Action'), ('role_change', 'Role / Position Change'), ('general', 'General Note')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=True, help_text='Private notes are only visible to the manager, not the employee.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_notes', to='crm.employee')),
            ],
            options={
                'verbose_name': 'HR Note',
                'verbose_name_plural': 'HR Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
