# Generated by Django 4.2.7 on 2025-07-10 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv4_address])),
                ('mac_address', models.CharField(blank=True, help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('matched', 'Matched to Asset'), ('ignored', 'Ignored'), ('pending', 'Pending Review')], default='new', max_length=20)),
                ('ports_open', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=dict)),
                ('os_info', models.JSONField(blank=True, default=dict)),
                ('hardware_info', models.JSONField(blank=True, default=dict)),
                ('software_info', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('scan_count', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in asset matching (0-1)')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw scan data')),
                ('notes', models.TextField(blank=True)),
                ('matched_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher numbers have higher priority')),
                ('conditions', models.JSONField(default=dict, help_text='JSON conditions for matching')),
                ('actions', models.JSONField(default=dict, help_text='JSON actions to perform when matched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(help_text='CIDR notation (e.g., 192.168.1.0/24)', max_length=18)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scan_frequency', models.IntegerField(default=3600, help_text='Scan frequency in seconds')),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scan_type', models.CharField(choices=[('discovery', 'Network Discovery'), ('port_scan', 'Port Scan'), ('service_scan', 'Service Detection'), ('os_detection', 'OS Detection'), ('full_scan', 'Full Scan')], default='discovery', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scan_options', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('devices_found', models.IntegerField(default=0)),
                ('new_devices', models.IntegerField(default=0)),
                ('updated_devices', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('network_ranges', models.ManyToManyField(to='discovery.networkrange')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('ports_scanned', models.JSONField(blank=True, default=list)),
                ('ports_open', models.JSONField(blank=True, default=list)),
                ('services_detected', models.JSONField(blank=True, default=dict)),
                ('os_fingerprint', models.JSONField(blank=True, default=dict)),
                ('is_alive', models.BooleanField(default=True)),
                ('scan_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('discovered_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='discovery.discovereddevice')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='discovery.scanjob')),
            ],
            options={
                'ordering': ['-scan_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='discovereddevice',
            name='network_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_devices', to='discovery.networkrange'),
        ),
        migrations.CreateModel(
            name='AssetDiscoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('discovered_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='discovery.discovereddevice')),
                ('scan_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='discovery.scanjob')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='discovereddevice',
            unique_together={('ip_address', 'network_range')},
        ),
    ]
